name = "illustris_julia"
uuid = "356b6c62-7396-11ec-31d4-55c52b5be5ca"
authors = ["Rahul Ramesh <rahul.ramesh@stud.uni-heidelberg.de>", "Dylan Nelson <dnelson@uni-heidelberg.de>"]
version = "0.1.0"

[deps]
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
